//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventType
    {
        public EventType()
        {
            this.Events = new HashSet<Event>();
            this.ReferenceTimes = new HashSet<ReferenceTime>();
        }
    
        public string Name { get; set; }
        public float SwimMiles { get; set; }
        public float CycleMiles { get; set; }
        public float RunMiles { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<ReferenceTime> ReferenceTimes { get; set; }
    }
}
